<!DOCTYPE html>
<html>
<head>
    <title>Monthly Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 15px;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #333;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .summary-table {
            width: 100%;
            margin-bottom: 20px;
            border-collapse: collapse;
        }
        .summary-table th {
            background-color: #f5f5f5;
            padding: 10px;
            text-align: left;
            border: 1px solid #ddd;
        }
        .summary-table td {
            padding: 10px;
            border: 1px solid #ddd;
        }
        .main-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        .main-table th {
            background-color: #333;
            color: white;
            padding: 8px;
            text-align: left;
            font-size: 11px;
        }
        .main-table td {
            padding: 8px;
            border: 1px solid #ddd;
            font-size: 11px;
        }
        .main-table tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            position: fixed;
            bottom: 20px;
            width: 100%;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
        .status-badge {
            padding: 3px 8px;
            border-radius: 3px;
            color: white;
            font-size: 10px;
        }
        .status-pending { background-color: #ffc107; color: #000; }
        .status-processing { background-color: #17a2b8; }
        .status-approved { background-color: #3498db; }
        .status-rejected { background-color: #dc3545; }
        .status-completed { background-color: #28a745; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Divine Infoservice Pvt. Ltd.</h1>
        <p><strong>Project: UOMS</strong></p>
        <p><strong>Monthly Report - {{ date('F', mktime(0, 0, 0, $month, 1)) }} {{ $year }}</strong></p>
        <p>Generated on: {{ date('d M Y, h:i A') }}</p>
    </div>

    <table class="summary-table">
        <tr>
            <th>Total Orders</th>
            <td>{{ $totalOrders }}</td>
            <th>Total Quantity</th>
            <td>{{ $totalQuantity }}</td>
        </tr>
        <tr>
            <th>Total Products</th>
            <td>{{ $totalProducts }}</td>
            <th>Period</th>
            <td>{{ date('F', mktime(0, 0, 0, $month, 1)) }} {{ $year }}</td>
        </tr>
    </table>

    <h3>Status Summary</h3>
    <table class="summary-table">
        <thead>
            <tr>
                <th>Status</th>
                <th>Count</th>
                <th>Percentage</th>
            </tr>
        </thead>
        <tbody>
            @foreach($statusSummary as $status => $count)
            <tr>
                <td>{{ ucfirst($status) }}</td>
                <td>{{ $count }}</td>
                <td>{{ $totalOrders > 0 ? number_format(($count / $totalOrders) * 100, 2) : 0 }}%</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <h3>Order Details</h3>
    @if($orders->isEmpty())
        <p>No orders found for this period.</p>
    @else
        <table class="main-table">
            <thead>
                <tr>
                    <th>Sr No</th>
                    <th>Order Number</th>
                    <th>Lab Manager</th>
                    <th>Department</th>
                    <th>Items</th>
                    <th>Status</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach($orders as $index => $order)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $order->order_number }}</td>
                    <td>{{ $order->user->name }}</td>
                    <td>{{ $order->user->department ?? 'N/A' }}</td>
                    <td>{{ $order->total_items }}</td>
                    <td>
                        <span class="status-badge status-{{ $order->status }}">
                            {{ ucfirst($order->status) }}
                        </span>
                    </td>
                    <td>{{ $order->created_at->format('d M Y') }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <div class="footer">
        <p>Page 1 of 1 | Generated by UOMS | &copy; {{ date('Y') }} Divine Infoservice Pvt. Ltd.</p>
    </div>
</body>
</html>
