<!DOCTYPE html>
<html>
<head>
    <title>{{ ucfirst($status) }} Orders Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 15px;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #333;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .summary-table {
            width: 100%;
            margin-bottom: 20px;
            border-collapse: collapse;
        }
        .summary-table th {
            background-color: #f5f5f5;
            padding: 10px;
            text-align: left;
            border: 1px solid #ddd;
        }
        .summary-table td {
            padding: 10px;
            border: 1px solid #ddd;
        }
        .main-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        .main-table th {
            background-color: #333;
            color: white;
            padding: 10px;
            text-align: left;
        }
        .main-table td {
            padding: 10px;
            border: 1px solid #ddd;
        }
        .main-table tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            position: fixed;
            bottom: 20px;
            width: 100%;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Divine Infoservice Pvt. Ltd.</h1>
        <p><strong>Project: UOMS</strong></p>
        <p><strong>{{ ucfirst($status) }} Orders Report</strong></p>
        <p>Generated on: {{ date('d M Y, h:i A') }}</p>
    </div>

    <table class="summary-table">
        <tr>
            <th>Total {{ ucfirst($status) }} Orders</th>
            <td>{{ $totalOrders }}</td>
            <th>Total Items</th>
            <td>{{ $totalQuantity }}</td>
        </tr>
    </table>

    <h3>Order Details</h3>
    @if($orders->isEmpty())
        <p>No {{ $status }} orders found.</p>
    @else
        <table class="main-table">
            <thead>
                <tr>
                    <th>Sr No</th>
                    <th>Order Number</th>
                    <th>Lab Manager</th>
                    <th>Department</th>
                    <th>Total Items</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach($orders as $index => $order)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $order->order_number }}</td>
                    <td>{{ $order->user->name }}</td>
                    <td>{{ $order->user->department ?? 'N/A' }}</td>
                    <td>{{ $order->total_items }}</td>
                    <td>{{ $order->created_at->format('d M Y') }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <div class="footer">
        <p>Page 1 of 1 | Generated by UOMS | &copy; {{ date('Y') }} Divine Infoservice Pvt. Ltd.</p>
    </div>
</body>
</html>
