<!DOCTYPE html>
<html>
<head>
    <title>Top Selling Products Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 15px;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #333;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .main-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        .main-table th {
            background-color: #333;
            color: white;
            padding: 10px;
            text-align: left;
        }
        .main-table td {
            padding: 10px;
            border: 1px solid #ddd;
        }
        .main-table tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .rank-1 { background-color: #ffd700; font-weight: bold; }
        .rank-2 { background-color: #c0c0c0; }
        .rank-3 { background-color: #cd7f32; }
        .footer {
            position: fixed;
            bottom: 20px;
            width: 100%;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Divine Infoservice Pvt. Ltd.</h1>
        <p><strong>Project: UOMS</strong></p>
        <p><strong>Top 10 Selling Products Report</strong></p>
        <p>Generated on: {{ date('d M Y, h:i A') }}</p>
    </div>

    @if($topProducts->isEmpty())
        <p>No products data available.</p>
    @else
        <table class="main-table">
            <thead>
                <tr>
                    <th>Rank</th>
                    <th>SKU</th>
                    <th>Product Name</th>
                    <th>Brand</th>
                    <th>Category</th>
                    <th>Total Ordered</th>
                </tr>
            </thead>
            <tbody>
                @foreach($topProducts as $index => $product)
                <tr class="@if($index == 0) rank-1 @elseif($index == 1) rank-2 @elseif($index == 2) rank-3 @endif">
                    <td>#{{ $index + 1 }}</td>
                    <td>{{ $product->sku }}</td>
                    <td>{{ $product->product_name }}</td>
                    <td>{{ $product->brand->name ?? 'N/A' }}</td>
                    <td>{{ $product->category->name ?? 'N/A' }}</td>
                    <td>{{ $product->total_ordered }} pcs</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <div class="footer">
        <p>Page 1 of 1 | Generated by UOMS | &copy; {{ date('Y') }} Divine Infoservice Pvt. Ltd.</p>
    </div>
</body>
</html>
